### ISSUE TITLE
Allow commonly used classes to be imported directly from `council`

### ISSUE THREAD

**Issue by D-Vaillant** [chain-ml/council#100]
Instead of:
```
from council.controllers import LLMController
from council.evaluators import LLMEvaluator
from council.agents import Agent
from council.filters import BasicFilter
```

Do:
```
from council import LLMController, LLMEvaluator, Agent, BasicFilter
```

It's much easier to remember and also extremely easy to implement (I can put in a PR). Basically everything in the Hello, World example should probably be able to be imported directly from `council` (or `council.models` which makes sense separately).

**Comment by aflament** [comment]
@D-Vaillant thank you for the suggestion, the PR is merged and will be part of 0.0.14 release of Council. Let us know if you have any additional comment or feedbacks.
