### ISSUE TITLE
when to update?

### ISSUE THREAD

**Issue by yiouyou** [chain-ml/council#67]
It was said the repo will updated every two weeks. Hope the project will become more popular.

**Comment by dvdmllr** [comment]
Hi @yiouyou,

We appreciate your interest and feedback. The engineering team is working in two weeks sprints to improve Council. While many sprints will result in a major feature addition and new release, some sprints will focus on minor incremental improvements to be included in a follow up release. 

Stay tuned for some of the exciting things we have planned. If there is a feature you want to see in Council, don't hesitate to let us know.
